# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit_num', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('pos', models.CharField(max_length=2)),
                ('dob', models.CharField(max_length=8)),
                ('nat', models.CharField(max_length=3)),
                ('apps', models.CharField(max_length=10)),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('mins', models.IntegerField()),
            ],
        ),
    ]
